# Testing meta data parsing
---
name: Test Docker Metadata

"on":
  push:
    branches:
      - main

jobs:
  docker-meta-test:
    name: Test Docker Metadata
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Initialize Docker metadata
        id: meta
        uses: docker/metadata-action@v5.2.0
        with:
          images: |
            ${{ github.actor }}/gh
          tags: |
            type=match,pattern=v(.*),group=1,value=2.29.0-r4
            type=match,pattern=v(\d+\.\d+\.\d+)-r.*,group=1,value=2.29.0-r4
            type=raw,value=latest
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Upload image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
