# Publish images to Docker Hub when a new release is published
---
name: Deploy to Docker Hub

on:
  release:
    types: [released]

jobs:
  docker-cd:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.3.0

      - name: Initialize Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: |
            ${{ github.actor }}/gh
          tags: |
            type=match,pattern=v(.*),group=1
            type=match,pattern=v(\d+\.\d+)\.\d+-r.*,group=1
            type=match,pattern=v(\d+\.\d+\.\d+)-r.*,group=1
            type=raw,value=latest
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Upload image to Docker Hub
        uses: docker/build-push-action@v6.18.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
